namespace BlobCopy.API.Models;

/// <summary>
/// Represents a single blob copy operation with complete state tracking.
/// </summary>
public class BlobCopyOperation
{
    /// <summary>
    /// Unique identifier for this copy operation (UUID v4, generated by backend).
    /// </summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// Source blob URI (validated Azure Blob Storage URI).
    /// Format: https://[account].blob.core.windows.net/[container]/[blob]
    /// </summary>
    public string SourceUri { get; set; } = string.Empty;

    /// <summary>
    /// Destination blob URI (validated Azure Blob Storage URI).
    /// Format: https://[account].blob.core.windows.net/[container]/[blob]
    /// </summary>
    public string DestinationUri { get; set; } = string.Empty;

    /// <summary>
    /// Current status of the copy operation.
    /// </summary>
    public BlobCopyStatus Status { get; set; } = BlobCopyStatus.Pending;

    /// <summary>
    /// Progress as percentage (0-100).
    /// Updated in real-time via SignalR.
    /// </summary>
    public decimal ProgressPercentage { get; set; } = 0m;

    /// <summary>
    /// Bytes transferred so far.
    /// </summary>
    public long BytesTransferred { get; set; } = 0;

    /// <summary>
    /// Total bytes to transfer.
    /// Known after initial blob properties fetch.
    /// </summary>
    public long TotalBytes { get; set; } = 0;

    /// <summary>
    /// Estimated time remaining in seconds.
    /// Calculated from current transfer rate.
    /// </summary>
    public int? EstimatedTimeRemaining { get; set; } = null;

    /// <summary>
    /// Error message if operation failed.
    /// Null if operation is pending, in-progress, or completed successfully.
    /// </summary>
    public string? ErrorMessage { get; set; } = null;

    /// <summary>
    /// List of validation or operational errors.
    /// Used for detailed error reporting in tests and API responses.
    /// </summary>
    public List<ValidationError>? Errors { get; set; } = null;

    /// <summary>
    /// Duration of the operation in seconds.
    /// Calculated from StartedAt and CompletedAt.
    /// </summary>
    public double? DurationSeconds { get; set; } = null;

    /// <summary>
    /// Name of the source blob (extracted from SourceUri).
    /// </summary>
    public string? SourceBlobName { get; set; } = null;

    /// <summary>
    /// Error code for programmatic handling.
    /// Used for retry logic, logging categorization.
    /// </summary>
    public string? ErrorCode { get; set; } = null;

    /// <summary>
    /// Timestamp when copy operation was initiated (ISO 8601).
    /// </summary>
    public DateTime StartedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Timestamp when copy operation completed (ISO 8601).
    /// Null if operation is still pending or in-progress.
    /// </summary>
    public DateTime? CompletedAt { get; set; } = null;

    /// <summary>
    /// Correlation ID for distributed tracing.
    /// Links this operation to Application Insights traces, logs, and requests.
    /// </summary>
    public string CorrelationId { get; set; } = string.Empty;

    /// <summary>
    /// Username/principal ID of the user who initiated the copy.
    /// Populated from Entra ID claims.
    /// </summary>
    public string InitiatedBy { get; set; } = string.Empty;

    /// <summary>
    /// Cancellation token state.
    /// True if user has requested cancellation; operation may still be completing.
    /// </summary>
    public bool CancellationRequested { get; set; } = false;
}
